version: '3'

services:

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: workers
      POSTGRES_PASSWORD: password
      POSTGRES_DB: workers

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080