version: '3'

services:
  app:
    build: .
    ports:
      - 3000:3000
      - 3001:3001
    env_file:
      - .env
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: workers
      POSTGRES_PASSWORD: password
      POSTGRES_DB: workers

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  s3:
    image: minio/minio
    command: ["server", "/data", "--console-address=:9001"]
    ports:
      - 9000:9000
      - 9001:9001